### ISSUE TITLE
Hardcoded API string

### ISSUE THREAD

**Issue by Pear0** [discord-java/discord.jar#1]
[Main.java]( https://github.com/discord-java/discord.jar/blob/master/example/src/main/java/discord/jar/example/Main.java#L10) contains a hardcoded API string. API Strings probably shouldn't be published in the repository, but It'd be difficult to remove from the history now.

**Comment by austinv11** [comment]
This is intentional. Reading from files causes too much overhead. We'll have to look into finding a workaround for the overhead involved in reading from files

**Comment by Pear0** [comment]
I'm glad you guys are focused on performance. That way we won't need sharding.
