### ISSUE TITLE
Is this an April Fools API made just for fun?

### ISSUE THREAD

**Issue by polyzium** [discord-java/discord.jar#14]

**Comment by AmiT177** [comment]
This is a real API that will replace JDA.

**Comment by xaanit** [comment]
austin.jar - Yesterday at 10:30 PM
@everyone this is a legit server please don't spam

As shown here (and plenty other times in the guild) this is a legitimate API that will replace all others.

**Comment by Almighty-Alpaca** [comment]
how dare you to accuse this legit api to be fake???  you should feel very bad...
