### ISSUE TITLE
[Efficiency] Use a proper build tool

### ISSUE THREAD

**Issue by FerusGrim** [discord-java/discord.jar#3]
We all know that Gradle is outdated. I'm not sure why you guys are sticking with relics from the past.

There's this new builder that's been picking up steam recently, you should [check it out](https://www.embarcadero.com/free-tools/ccompiler?utm_source=google&utm_medium=cpc&utm_campaign=embcplusplus&utm_content=brand&utm_term=c%2B%2B%20compiler&gclid=CjwKEAjw_PfGBRDW_sutqMbQsmMSJAAMpUapq6n_lQp4kLrUM4rUHUqzRIlgnQn9uGtDwFJeCvVKpxoClKfw_wcB).

**Comment by Pear0** [comment]
We should use Bazel. Google uses Bazel and they handle billions of users.
